DROP VIEW IF EXISTS 'VW_CATEGORY';
DROP VIEW IF EXISTS 'VW_SUB_CATEGORY';
DROP VIEW IF EXISTS 'VW_ITEM';
DROP VIEW IF EXISTS 'VW_SHOP';

CREATE VIEW 'VW_CATEGORY' AS SELECT *, NAME_TC AS NAME FROM CATEGORY;
CREATE VIEW 'VW_SUB_CATEGORY' AS SELECT *, NAME_TC AS NAME FROM SUB_CATEGORY;
CREATE VIEW 'VW_ITEM' AS SELECT *, BRAND_TC AS BRAND, NAME_TC AS NAME FROM ITEM;
CREATE VIEW 'VW_SHOP' AS SELECT *, NAME_TC AS NAME FROM SHOP;

