CREATE TABLE IF NOT EXISTS 'CATEGORY' (
  '_id' INTEGER PRIMARY KEY AUTOINCREMENT,
  'NAME_EN' TEXT NOT NULL,
  'NAME_TC' TEXT NOT NULL,
  'NAME_SC' TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS 'SUB_CATEGORY' (
  '_id' INTEGER PRIMARY KEY AUTOINCREMENT,
  'CATEGORY_ID' INTEGER NOT NULL,
  'NAME_EN' TEXT NOT NULL,
  'NAME_TC' TEXT NOT NULL,
  'NAME_SC' TEXT NOT NULL,
  FOREIGN KEY ('CATEGORY_ID') REFERENCES 'CATEGORY' ('_id') 
);

CREATE TABLE IF NOT EXISTS 'ITEM' (
  '_id' INTEGER PRIMARY KEY AUTOINCREMENT,
  'ITEM_CODE' TEXT NOT NULL,
  'BARCODE' TEXT NULL,
  'SUB_CATEGORY_ID' INTEGER NOT NULL,
  'ORDER_INDEX' INT NULL,
  'BRAND_EN' TEXT NULL,
  'NAME_EN' TEXT NULL,
  'BRAND_TC' TEXT NULL,
  'NAME_TC' TEXT NULL,
  'BRAND_SC' TEXT NULL,
  'NAME_SC' TEXT NULL,
  FOREIGN KEY ('SUB_CATEGORY_ID') REFERENCES 'SUB_CATEGORY' ('_id') 
);

CREATE INDEX ITEM_INDEX_1 ON ITEM('SUB_CATEGORY_ID');
CREATE UNIQUE INDEX ITEM_INDEX_2 ON ITEM('ITEM_CODE');
CREATE UNIQUE INDEX ITEM_INDEX_3 ON ITEM('BARCODE');


CREATE TABLE IF NOT EXISTS 'SHOP' (
  '_id' INTEGER PRIMARY KEY AUTOINCREMENT,
  'ORDER_INDEX' INTEGER NULL,
  'NAME_EN' TEXT NULL,
  'NAME_TC' TEXT NULL,
  'NAME_SC' TEXT NULL
);

CREATE TABLE IF NOT EXISTS 'SHOP_ITEM' (
  '_id' INTEGER PRIMARY KEY AUTOINCREMENT,
  'SHOP_ID' INTEGER NOT NULL,
  'ITEM_ID' INTEGER NOT NULL,
  'PRICE' REAL NOT NULL,
  'EFF_DATE' TEXT NOT NULL,
  'PREV_PRICE' REAL NULL,
  FOREIGN KEY ('SHOP_ID') REFERENCES 'SHOP' ('_ID') ,
  FOREIGN KEY ('ITEM_ID') REFERENCES 'ITEM' ('_ID') 
);

CREATE INDEX SHOP_ITEM_INDEX_1 ON SHOP_ITEM('SHOP_ID');
CREATE INDEX SHOP_ITEM_INDEX_2 ON SHOP_ITEM('ITEM_ID');


CREATE TABLE IF NOT EXISTS 'QUERY_HIST' (
  '_id' INTEGER PRIMARY KEY AUTOINCREMENT,
  'ITEM_ID' INTEGER NOT NULL,
  'QUERY_DATE' TEXT NOT NULL,
  'QUERY_COUNT' INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY ('ITEM_ID') REFERENCES 'ITEM' ('_ID') 
);

CREATE INDEX QUERY_HIST_INDEX_1 ON QUERY_HIST('ITEM_ID');
